apiVersion: rbac.authrization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rolebindingName}}
  namespace: {{ .Values.namespace.name}}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceaccountName}}
    namespace: {{ .Values.namespace.name}}
roleRef:
  kind: Role
  name: {{ .Values.roleName}}
  apiGroup: [""]
    