apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName}}
  namespace: {{ .Values.namespace.name}}
spec:
  selector: 
    {{- toYaml .Values.metadata.labels | nindent 4}}
  type: {{ .Values.service.type}}
  ports:
    - targetPort: {{ .Values.service.targetport}}
      port: {{ .Values.service.targetport}}
      protocol: {{ .Values.service.protocol}}